### ISSUE TITLE
Including urls does not work

### ISSUE THREAD

**Issue by icu0755** [byteweaver/django-filemanager#3]
Urls including will not work in the way shown in Readme.

Try removing tailing $ in the base route:

url(r'^your-url/$', include('filemanager.urls', namespace='filemanager'))

should be changed to

url(r'^your-url/', include('filemanager.urls', namespace='filemanager')),

**Comment by noxan** [comment]
That is very true... thanks for the hint!

Do you prefer to submit a pull request (keep track of the credits in the git log) or should I just shortly fix the issue myself?

**Comment by icu0755** [comment]
I though it would be an overhead to do pull request. So feel free to fix it.
